import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";
import {
  cacheRoot,
  deterministicPatches,
  generatedDir,
  hostDir,
  jsOnlyEngineFlags,
  patchDir,
  projectRoot,
  upstreamDir,
} from "./c2js.config.mjs";
import { run } from "./common.mjs";
import {
  collectObjects,
  compileCore,
  compileLua,
  compilePortObjects,
} from "./compile.mjs";
import { validateLinkedEngine } from "./verify.mjs";

function sortedFiles(dir, predicate) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    const st = statSync(path);
    if (st.isDirectory()) out.push(...sortedFiles(path, predicate));
    else if (!predicate || predicate(path)) out.push(path);
  }
  return out.sort();
}

function commandOutput(cmd, args) {
  return execFileSync(cmd, args, {
    cwd: projectRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

function c2jsInputFiles() {
  return [
    ...deterministicPatches.map((name) => join(patchDir, name)),
    ...sortedFiles(
      hostDir,
      (path) => path.endsWith(".c") || path.endsWith(".h"),
    ),
    ...sortedFiles(join(projectRoot, "tools/c2js"), (path) =>
      path.endsWith(".mjs"),
    ),
    join(projectRoot, "package.json"),
  ].filter((path) => existsSync(path));
}

export function buildSignature() {
  const hash = createHash("sha256");
  const upstreamCommit = commandOutput("git", [
    "-C",
    upstreamDir,
    "rev-parse",
    "HEAD",
  ]);
  const files = c2jsInputFiles();

  hash.update(`upstream\0${upstreamCommit}\n`);
  for (const file of files) {
    const rel = relative(projectRoot, file);
    hash.update(`file\0${rel}\0`);
    hash.update(readFileSync(file));
    hash.update("\n");
  }

  return {
    sha256: hash.digest("hex"),
    upstreamCommit,
    emccVersion: commandOutput("emcc", ["--version"]).split(/\r?\n/)[0],
    clangVersion: commandOutput("clang", ["--version"]).split(/\r?\n/)[0],
    files: files.map((file) => relative(projectRoot, file)),
  };
}

function generatedBanner(signature) {
  return [
    "// Generated by npm run c2js:update. Do not edit by hand.",
    `// c2js-input-sha256: ${signature.sha256}`,
    `// upstream: ${signature.upstreamCommit}`,
    "",
  ].join("\n");
}

function stripUnusedExternalLoaders(modulePath) {
  const before = readFileSync(modulePath, "utf8");
  const after = before.replace(
    /readAsync = async url => \{\n\s+var response = await fetch\(url, \{\n\s+credentials: "same-origin"\n\s+\}\);\n\s+if \(response\.ok\) \{\n\s+return response\.arrayBuffer\(\);\n\s+\}\n\s+throw new Error\(response\.status \+ " : " \+ response\.url\);\n\s+\};/,
    'readAsync = async () => { throw new Error("external resource loading disabled"); };',
  );
  if (after !== before) {
    writeFileSync(modulePath, after);
    console.log("stripped unused generated fetch loader");
  }
}

export function linkEngine() {
  compileCore();
  compileLua();
  compilePortObjects();

  const linkDir = join(cacheRoot, "link");
  rmSync(linkDir, { recursive: true, force: true });
  mkdirSync(linkDir, { recursive: true });

  const modulePath = join(linkDir, "nethack-core.mjs");
  const objects = collectObjects([
    join(cacheRoot, "core-objects"),
    join(cacheRoot, "lua-objects"),
    join(cacheRoot, "port-objects"),
  ]);
  run("emcc", [
    ...objects,
    ...jsOnlyEngineFlags,
    "-Wl,--gc-sections",
    "-Wl,--error-limit=0",
    "-sERROR_ON_UNDEFINED_SYMBOLS=1",
    "--no-entry",
    "-o",
    modulePath,
  ]);
  stripUnusedExternalLoaders(modulePath);
  validateLinkedEngine(modulePath);
  console.log(`linked ${modulePath}`);
  return modulePath;
}

export function updateGenerated() {
  const modulePath = linkEngine();
  const signature = buildSignature();
  mkdirSync(generatedDir, { recursive: true });
  const target = join(generatedDir, "nethack-core.mjs");
  copyFileSync(modulePath, target);
  writeFileSync(
    target,
    `${generatedBanner(signature)}${readFileSync(target, "utf8")}`,
  );
  run(process.execPath, [join(projectRoot, "tools/c2js/format.mjs"), target]);
  console.log(`c2js input sha256 ${signature.sha256}`);
  console.log(
    `c2js toolchain ${signature.emccVersion}; ${signature.clangVersion}`,
  );
  console.log(`updated ${target}`);
}
